# -*- coding: utf-8 -*-
"""MTFall2025_Part II

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jda4mXmKd3gcHrXQKE8BAvk6JY7NKLRg
"""

# 1. A program that calculates the area of a rectangle
Width = float(input("Enter the width of a rectangle : " ))
Height = float(input("Enter the Height of a rectangle : " ))
Area_of_a_rectangle = Width * Height

print ("The result for your area of a rectangle is " , Area_of_a_rectangle )

# Enter the width of a rectangle : 20
# Enter the Height of a rectangle : 20
# The result for your area of a rectangle is  400.0

# 2. A program that takes two numbers as input and displays their: sum , Difference, Product, Quotient, Remainder

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

sum = num1 + num2
print("Sum:", sum)

difference = num1 - num2
print ("Difference:", difference)

product = num1 * num2
print("Product:", product)

if num2 != 0:
    quotient = num1 / num2
    print("Quotient:", quotient)
    remainder = num1 % num2
    print("Remainder:", remainder)
else:
    print("The result is Undefined (Cannot divide by zero).")
    print( "The result is Undefined (Cannot divide by zero)")

# Enter the first number: 4
# Enter the second number: 2
# Sum: 6.0
# Difference: 2.0
# Product: 8.0
# Quotient: 2.0
# Remainder: 0.0

# Enter the first number: 4
# Enter the second number: 0
# Sum: 4.0
# Difference: 4.0
# Product: 0.0
# The result is Undefined (Cannot divide by zero).
# The result is Undefined (Cannot divide by zero)

# 3. a program that converts minutes into hours and remaining minutes
Minutes = int(input("Enter minutes to convert to into hours and remaining minutes: "))

if Minutes < 0 :
    print("ERROR >>> Invalid input.Enter only positive numbers!!!")

else :
    Hours = Minutes//60
    Remaining_minutes = Minutes % 60

    print (f"{Minutes} minutes is {Hours} hours and {Remaining_minutes} minutes.")

# Enter minutes to convert to into hours and remaining minutes: 135
# 135 minutes is 2 hours and 15 minutes.

# Enter minutes to convert to into hours and remaining minutes: -135
# ERROR >>> Invalid input.Enter only positive numbers!!!

#4. A list with the numbers [10, 20, 30, 40, 50] will be added , removed.

Original_List = [10, 20, 30, 40, 50]
print("Numbers of the original List are", Original_List)

Original_List.append(60)
print("Numbers of the added List are", Original_List)

Original_List.remove(30)
print("Numbers of the removed List are", Original_List)

print ("Final list is ", Original_List)

# Numbers of the original List are [10, 20, 30, 40, 50]
# Numbers of the added List are [10, 20, 30, 40, 50, 60]
# Numbers of the removed List are [10, 20, 40, 50, 60]
# Final list is  [10, 20, 40, 50, 60]

#5. Create a text file called greetings.txt containing a few lines of text.Then write a Python program to:

# Create and write to the file
with open("greetings.txt", "w") as file:
    file.write("Dear Prof Khin,\n")
    file.write("My name is Yin Htwe and my nickname is Phoe Kiit (PK).\n")
    file.write("I am a dog-person.\n")
    file.write("I am pursuing SDS in Parami University.\n")
    file.write("I am originally from Naunghkio which is situated in Northern Shan State.\n")
    file.write("I am very happy to teach with you.\n")

print("greetings.txt file created successfully!\n")

# Open and read the file
try:
    with open ("greetings.txt" , "r") as file:
      for line in file:
        print(line.strip())# .strip() removes any unwanted blank lines.

except FileNotFoundError:
    print("File not found. Please make sure greetings.txt exists.")


# greetings.txt file created successfully!

# Dear Prof Khin,
# My name is Yin Htwe and my nickname is Phoe Kiit (PK).
# I am a dog-person.
# I am pursuing SDS in Parami University.
# I am originally from Naunghkio which is situated in Northern Shan State.
# I am very happy to teach with you.