# -*- coding: utf-8 -*-
"""Yin_Htwe_Ch5ProgrammingExercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZveoxhjLwxzcQK3EX6HcY0f2opQmH2w

# Chapter 5 Sequences: Strings, Lists and Files
"""

#1.  program that accepts a quiz score as an input and prints out the corresponding grade

Score = input("Enter your quiz score (0-5): ")

score = Score.upper() #Convert input to uppercase to handle 'O' or 'o'

if score == '5':
    print("Grade: A")
elif score == '4':
    print("Grade: B")
elif score == '3':
    print("Grade: C")
elif score == '2':
    print("Grade: D")
elif score == '1' or score == 'O':
    print("Grade: F")
else:
    print("Error: Invalid score. Please enter a number from 0 to 5 or O.")


# Output
# Enter your quiz score (0-5): 0
# Grade: F
# Enter your quiz score (0-5): 1
# Grade: F
# Enter your quiz score (0-5): 2
# Grade: D
# Enter your quiz score (0-5): 3
# Grade: C
# Enter your quiz score (0-5): 4
# Grade: B
# Enter your quiz score (0-5): 5
# Grade: A
# Enter your quiz score (0-5): 6
# Error: Invalid score. Please enter a number from 0 to 5 or O.

#2  program that counts the number of words in a sentence entered by the user.

sentence = input("Enter a sentence: ")

words = sentence.split() # Split the sentence into words based on spaces

word_count = len(words) # Count the number of words

print("Number of words in the sentence:", word_count)

# Enter a sentence: Phoe Kitt is pursuing SDS in Parami University.
# Number of words in the sentence: 8

#3. a program that calculates the average word length in a sentence entered by the user.

sentence = input("Enter a sentence: ")

words = sentence.split()

if len(words) == 0:
    print("No words in the sentence to calculate average length.")
else:
    total_length = sum(len(word) for word in words) # Calculate total number of characters in all words

    average_length = total_length / len(words) # Calculate average word length

    print("total_length:" , total_length )
    print("Number of words in the sentence:", len(words))
    print("Average word length:", average_length)

# Enter a sentence: I am originally from Naunghkio
# total_length: 26
# Number of words in the sentence: 5
# Average word length: 5.2