# -*- coding: utf-8 -*-
"""Yin_Htwe_Ch2ProgrammingExercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uY3VSxj1atS67Qn39Jpew1IQ-_fbYH2K
"""

#1. Finding the average of three exam scores.
def main():
   print("This program computes the average of three exam scores.")
   score1, score2, score3 = eval(input("Enter three scores separated by a comma: "))
   average = (score1 + score2 + score3)/3
   print("The average of the scores is:", average)
main()

#Output :
#This program computes the average of three exam scores.
#Enter three scores separated by a comma: 100,200,700
#The average of the scores is: 333.3333333333333

#2. A program that converts distances measured in kilometers to miles. One kilometer is approximately 0.62 miles.
def kilometers_to_miles (km) :
  miles = 0.62 * km
  return miles

km = float(input("Enter distance in kilometers: "))
miles = kilometers_to_miles(km)
print(f"{km} kilometers is approximately {miles} miles.")

#Output :
#Enter distance in kilometers: 100
#100.0 kilometers is approximately 62.0 miles.

#3.A Python program that counts the number of vowels (a, e, i, o, u) in a given string

def count_vowels(string):
    vowels = "aeiouAEIOU"
    count = 0
    for character in string:
        if character in vowels:
            count += 1

    return count

user_input = input("Enter a string: ")
vowel_count = count_vowels(user_input)

print(f"The number of vowels in the string is: {vowel_count}")

#Output :
#Enter a string: Where is an umbrella?
#The number of vowels in the string is: 7

#4. An interactive Python calculator program.
for _ in range(100):
    try:
        expression = input("Enter a mathematical expression (or 'quit' to exit): ")

        if expression.lower() == 'quit':
            print("Exiting the calculator.")
            break

        result = eval(expression)
        print(f"Result: {result}")

    except Exception as e:
        print(f"Error: Invalid expression. {e}")

#Output :
#Enter a mathematical expression (or 'quit' to exit): 1000-10
#Result: 990
#Enter a mathematical expression (or 'quit' to exit): 100-10
#Result: 90
#Enter a mathematical expression (or 'quit' to exit): Happy
#Error: Invalid expression. name 'Happy' is not defined
#Enter a mathematical expression (or 'quit' to exit): quit
#Exiting the calculator.

#5. Program with a loop so that it executes 5 times before quitting. Each time through the loop, the program should get another temperature from the user and print the converted value. A program to convert Celsius temps to Fahrenheit.

def main():
    for i in range(5):   # repeat 5 times
        celsius = eval(input("What is the Celsius temperature? "))
        fahrenheit = 9/5 * celsius + 32
        print("The temperature is", fahrenheit, "degrees Fahrenheit.")
main()

#Output :
#What is the Celsius temperature? 20
##The temperature is 68.0 degrees Fahrenheit.
#What is the Celsius temperature? 30
#The temperature is 86.0 degrees Fahrenheit.
#What is the Celsius temperature? 40
#The temperature is 104.0 degrees Fahrenheit.
#What is the Celsius temperature? 50
#The temperature is 122.0 degrees Fahrenheit.
#What is the Celsius temperature? 60
#The temperature is 140.0 degrees Fahrenheit.

