# -*- coding: utf-8 -*-
"""Yin_Htwe_FPFall2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMTGUlUlrXdEw8-Yqcg830uIcYH-W_0w

# SECTION: A
## CS 210 - PROGRAMMING WITH PYTHON
### INSTRUCTOR : DR. KHIN SANDAR KYAW
### STUDENT : MR YIN HTWE

ATM Simulation

Project Description: Simulate a simple ATM system including the following menu:
check balance,
deposit money, withdraw money, and exit.

Features:
• Define functions for checking balance, depositing, and withdrawing.

• Use a loop to allow users to perform multiple transactions until they choose to exit.

• Use decision structures to handle incorrect PINs, insufficient funds, or invalid inputs.

• Use Boolean flags for login success and session control. (100 marks)
"""

def check_balance(current_balance):
    print(f"Your Current Balance: ${current_balance:.2f} ")

def deposit_money(current_balance):
    try:
        amount = float(input("Enter amount to deposit: $"))
        if amount > 0:
            current_balance += amount
            print(f"Successfully deposited ${amount:.2f}.")
        else:
            print("Error: Deposit amount must be positive.")
    except ValueError:
        print("Error: Invalid input. Please enter a number.")
    return current_balance

def withdraw_money(current_balance):
    try:
        amount = float(input("Enter amount to withdraw: $"))
        if amount <= 0:
            print("Error: Withdrawal amount must be positive.")
        elif amount > current_balance:
            print("Error: Insufficient funds.") # Handling insufficient funds
        else:
            current_balance -= amount
            print(f"${amount:.2f} withdrawn successfully.")
    except ValueError:
        print("Error: Invalid input. Please enter a number.")
    return current_balance

def main():
    print("---- NEW ACCOUNT SETUP ----")
    CORRECT_PIN = ""
    # Loop to ensure the user creates a valid 4-digit PIN
    while len(CORRECT_PIN) != 4 or not CORRECT_PIN.isdigit():
        CORRECT_PIN = input("Create a 4-digit PIN for your new account: ")
        if len(CORRECT_PIN) != 4 or not CORRECT_PIN.isdigit():
            print("Error: PIN must be exactly 4 numeric digits.")

    print("Account created successfully! Please Log in.\n")

    balance = 0.0
    while True:
        try:
            start_amount = float(input("Enter your initial deposit amount: $"))
            if start_amount >= 0:
                balance = start_amount
                break
            else:
                print("Error: Amount cannot be negative.")
        except ValueError:
            print("Error: Please enter a valid number.")

    print(f"Account created with ${balance:.2f}. Please Log in.\n")

    # Boolean Flags
    is_logged_in = False
    session_active = False

    # Login Process
    attempts = 3
    while attempts > 0 and not is_logged_in:
        user_pin = input("Enter your PIN to login: ")

        if user_pin == CORRECT_PIN:
            is_logged_in = True
            session_active = True
            print("Login Successful!")
        else:
            attempts -= 1
            print(f"Incorrect PIN. Attempts remaining: {attempts}")

    # Main Transaction Loop
    if is_logged_in:
        while session_active:
            print("\n------------- ATM MENU -------------")
            print("1. Check Balance")
            print("2. Deposit Money")
            print("3. Withdraw Money")
            print("4. Exit")
            print("---------------------------------------")

            choice = input("Select an option (1-4): ")

            if choice == '1':
                check_balance(balance)
            elif choice == '2':
                balance = deposit_money(balance)
            elif choice == '3':
                balance = withdraw_money(balance)
            elif choice == '4':
                print("Thank you for using the ATM. Goodbye!")
                session_active = False
            else:
                print("Invalid selection. Please choose 1, 2, 3 or 4.")
    else:
        print("System locked due to security reasons.")

if __name__ == "__main__":
    main()


# ---- NEW ACCOUNT SETUP ----
# Create a 4-digit PIN for your new account: 1234
# Account created successfully! Please Log in.

# Enter your initial deposit amount: $1000
# Account created with $1000.00. Please Log in.

# Enter your PIN to login: 1233
# Incorrect PIN. Attempts remaining: 2
# Enter your PIN to login: 1234
# Login Successful!

# ------------- ATM MENU -------------
# 1. Check Balance
# 2. Deposit Money
# 3. Withdraw Money
# 4. Exit
# ---------------------------------------
# Select an option (1-4): 1
# Your Current Balance: $1000.00

# ------------- ATM MENU -------------
# 1. Check Balance
# 2. Deposit Money
# 3. Withdraw Money
# 4. Exit
# ---------------------------------------
# Select an option (1-4): 2
# Enter amount to deposit: $200
# Successfully deposited $200.00.

# ------------- ATM MENU -------------
# 1. Check Balance
# 2. Deposit Money
# 3. Withdraw Money
# 4. Exit
# ---------------------------------------
# Select an option (1-4): 3
# Enter amount to withdraw: $150
# $150.00 withdrawn successfully.

# ------------- ATM MENU -------------
# 1. Check Balance
# 2. Deposit Money
# 3. Withdraw Money
# 4. Exit
# ---------------------------------------
# Select an option (1-4): 1
# Your Current Balance: $1050.00

# ------------- ATM MENU -------------
# 1. Check Balance
# 2. Deposit Money
# 3. Withdraw Money
# 4. Exit
# ---------------------------------------
# Select an option (1-4): 4
# Thank you for using the ATM. Goodbye!

"""Number Guessing Game with Score Tracker

Project Description: A user guesses a randomly generated number between 1 and 100.

Features:

• Use a function to run the guessing game logic.

• Use a loop to allow multiple attempts and games.

• Use decision structures to provide feedback: "Too high", "Too low", or "Correct!".

• Track the number of attempts and use Boolean expressions to end the game on a correct guess
or user quit. (100 marks)
"""

import random

def play_one_round():
    target_number = random.randint(1, 100)
    attempts = 0
    game_active = True # Boolean flag for session control

    print("Guess the number between 1 and 100. Type 'q' to quit.")

    while game_active:
        user_input = input("Enter your guess: ")

        #Check if user wants to quit
        if user_input.lower() == 'q':
            print("You quit the game.")
            return False # Return False because they didn't win

        # Validate input is a number
        if not user_input.isdigit():
            print("Invalid input. Please enter a number or 'q'.")
            continue # Skip to the start of the loop

        # Game Logic
        guess = int(user_input)
        attempts += 1

        if guess == target_number:
            print(f"Correct! You guessed the number in {attempts} attempts.")
            return True # Return True because they won
        elif guess > target_number:
            print("Too high! Try again.")
        else:
            print("Too low! Try again.")

def main():
    print("=== Welcome to the Number Guessing Game ===")
    total_games_played = 0
    games_won = 0
    running = True # Boolean flag for main application loop

    while running:
        choice = input("Do you want to play a game? (y/n): ").lower()

        if choice == 'y':
            total_games_played += 1
            has_won = play_one_round()

            if has_won:
                games_won += 1

        elif choice == 'n':
            print("Thanks for playing!")
            print(f"Total games played: {total_games_played}")
            print(f"Games won: {games_won}")
            running = False # End the loop

        else:
            print("Invalid choice. Please enter 'y' or 'n'.")

if __name__ == "__main__":
    main()


# === Welcome to the Number Guessing Game ===
# Do you want to play a game? (y/n): y
# Guess the number between 1 and 100. Type 'q' to quit.
# Enter your guess: 40
# Too high! Try again.
# Enter your guess: 20
# Too low! Try again.
# Enter your guess: 30
# Too high! Try again.
# Enter your guess: 25
# Too high! Try again.
# Enter your guess: 23
# Too low! Try again.
# Enter your guess: 24
# Correct! You guessed the number in 6 attempts.
# Do you want to play a game? (y/n): y
# Guess the number between 1 and 100. Type 'q' to quit.
# Enter your guess: q
# You quit the game.
# Do you want to play a game? (y/n): n
# Thanks for playing!
# Total games played: 2
# Games won: 1