# -*- coding: utf-8 -*-
"""Yin_Htwe_Ch6ProgrammingExercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17h_OHoQJW2PNSGUY5f_a8cCwvegxqWhR
"""

# 1. A program to print the lyrics of the song "Old MacDonald." My program should print the lyrics for five different animals.
animals_and_sounds = [
    ("cow", "moo"),
    ("pig", "oink"),
    ("duck", "quack"),
    ("sheep", "baa"),
    ("cat", "meow"), ]

print("--- Old MacDonald Had A Farm Lyrics ---")
print()

for animal, sound in animals_and_sounds:
    print("Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!")
    print(f"And on that farm he had a {animal}, Ee-igh, Ee-igh, Oh!")
    print(f"With a {sound}, {sound} here and a {sound}, {sound} there.")
    print(f"Here a {sound}, there a {sound}, everywhere a {sound}, {sound}.")
    print("Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!")
    print()


# --- Old MacDonald Had A Farm Lyrics ---

# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!
# And on that farm he had a cow, Ee-igh, Ee-igh, Oh!
# With a moo, moo here and a moo, moo there.
# Here a moo, there a moo, everywhere a moo, moo.
# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!

# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!
# And on that farm he had a pig, Ee-igh, Ee-igh, Oh!
# With a oink, oink here and a oink, oink there.
# Here a oink, there a oink, everywhere a oink, oink.
# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!

# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!
# And on that farm he had a duck, Ee-igh, Ee-igh, Oh!
# With a quack, quack here and a quack, quack there.
# Here a quack, there a quack, everywhere a quack, quack.
# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!

# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!
# And on that farm he had a sheep, Ee-igh, Ee-igh, Oh!
# With a baa, baa here and a baa, baa there.
# Here a baa, there a baa, everywhere a baa, baa.
# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!

# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!
# And on that farm he had a cat, Ee-igh, Ee-igh, Oh!
# With a meow, meow here and a meow, meow there.
# Here a meow, there a meow, everywhere a meow, meow.
# Old MacDonald had a farm, Ee-igh, Ee-igh, Oh!

# 2. Definitions for these functions

import math

def sphereArea(r):
    A = 4 * math.pi * r ** 2
    return A

def sphere_Volume(r):
    V = (4 / 3) * math.pi * r ** 3
    return V

radius = 10
print(round(sphereArea(radius),2))
print(round(sphere_Volume(radius),2))

# 1256.64
# 4188.79

# 3. A function that computes the area of a triangle given the length of its three sides as parameters.

def area_of_triangle(base,height):
  Area = 0.5 * base * height
  return Area

b, h = 5 , 10
print("The area of a triangle is" ,area_of_triangle(b,h))

#The area of a triangle is 25.0

#4. A function which provides a password is strong or not

def is_strong_password(pwd):
    failures = []

    if len(pwd) < 8:
        failures.append(f"Length ({len(pwd)}): Must be at least 8 characters long.")

    if not any(char.isupper() for char in pwd):
        failures.append("Uppercase: Must contain at least one uppercase letter.")

    if not any(char.islower() for char in pwd):
        failures.append("Lowercase: Must contain at least one lowercase letter.")

    if not any(char.isdigit() for char in pwd):
        failures.append("Digit: Must contain at least one digit (0-9).")

    if not failures: # If the list of failures is empty, the password is strong.
        return "This password is strong!"

    else:
        print("FAILED Criteria:") # Print failures before returning False
        for f in failures:
            print(f" * {f}")
        return "This password is weak!"

Pw = "batman"
print(f"The example of my password is {Pw}.")
print(is_strong_password(Pw))
print()
Pw = "A1STRONGpassword@"
print(f"The example of my password is {Pw}.")
print(is_strong_password(Pw))

# The example of my password is batman.
# FAILED Criteria:
#  * Length (6): Must be at least 8 characters long.
#  * Uppercase: Must contain at least one uppercase letter.
#  * Digit: Must contain at least one digit (0-9).
# This password is weak!

# The example of my password is A1STRONGpassword@.
# This password is strong!