# -*- coding: utf-8 -*-
"""Yin_Htwe_Ch3ProgrammingExercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kuOJbITLiFJ6HO5nVY1BZu0YdivcA0F
"""

#1. A program that determines the distance to a lightning strike based on the time elapsed between the flash and the sound of thunder

The_speed_of_sound_per_second = 1100
Feet_per_mile = 5280
Time_sec = float(input("Enter the time elapsed between the flash and the sound of thunder (in seconds): "))

# Calculate distance in feet
distance_to_the_lightning_strike_in_feet  = Time_sec * The_speed_of_sound_per_second
# Convert distance to miles
distance_miles = distance_to_the_lightning_strike_in_feet / Feet_per_mile

print(f"The lightning strike is approximately {distance_miles:.2f} miles away.") # :.2f displays with exactly two digits after the decimal point.

#Output :
#Enter the time elapsed between the flash and the sound of thunder (in seconds): 1100
#The lightning strike is approximately 229.17 miles away.

#2.A program that calculates the cost of an order

coffee_price_per_pound = 10.50
shipping_cost_per_pound = 0.86
fixed_overhead = 1.50

pounds_of_coffee = float(input("Enter the number of pounds of coffee: "))

# Calculate the total cost of coffee
coffee_cost = coffee_price_per_pound * pounds_of_coffee

# Calculate the total shipping cost
shipping_cost = shipping_cost_per_pound * pounds_of_coffee

# Total order cost
total_cost = coffee_cost + shipping_cost + fixed_overhead

# Display the result
print(f"\nCost of coffee: ${coffee_cost:.2f}")
print(f"Shipping cost: ${shipping_cost:.2f}")
print(f"Fixed overhead: ${fixed_overhead:.2f}")
print(f"Total cost of the order: ${total_cost:.2f}")


#Enter the number of pounds of coffee: 10
#Cost of coffee: $105.00
#Shipping cost: $8.60
#Fixed overhead: $1.50
#Total cost of the order: $115.10

#3 A program to find the sum of the first n natural numbers

The_value_of_n = int(input("Enter a positive integer , n : "))

sum_n = The_value_of_n * (The_value_of_n + 1) // 2  # Use integer division to avoid decimals

print(f"The sum of the first {The_value_of_n } natural numbers is: {sum_n}")

#Output
#Enter a positive integer , n : 3
#The sum of the first 3 natural numbers is: 6