# -*- coding: utf-8 -*-
"""Yin Htwe_Ch8ProgrammingExercise..

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZaNKIHmUnY24H93kXmD1ZvpohpfkEDI
"""

#1. A program that computes and outputs the nth Fibonacci number, where n is a value

n = int(input("Enter the value of n to find the nth Fibonacci number: "))

if n <= 0:
    print("Please enter a positive integer (1, 2, 3, ...).")
elif n == 1:
    print(f"The 1st Fibonacci number is: 1")
elif n == 2:
    print(f"The 2nd Fibonacci number is: 1")

    # Calculation for n > 2 using a while loop
else:
    a = 1  # The (n-2)th number
    b = 1  # The (n-1)th number
    count = 3 # We start counting from the 3rd number since we already have the first two
    while count <= n:

          next_fib = a + b
          a = b
          b = next_fib
          count += 1

    print(f"The {n}th Fibonacci number is: {b}")

# Enter the value of n to find the nth Fibonacci number: 20
# The 20th Fibonacci number is: 6765

# 2. A program that uses a while loop to determine how long it takes for an investment to double at a given interest rate.

rate_input = float(input("Enter the annualized interest rate: "))
rate_decimal = rate_input / 100
initial_investment = 1.0
current_balance = initial_investment
target_balance = initial_investment * 2
years = 0

while current_balance < target_balance:
        interest = current_balance * rate_decimal
        current_balance += interest
        years += 1

print(f"Interest Rate: {rate_input}%")
print(f"It will take", years, "years for the investment to double.")

# Enter the annualized interest rate: 5
# Interest Rate: 5.0%
# It will take 15 years for the investment to double.

#3. A program that accepts a value of n as input and determines if the value is prime. If n is not prime, your program should quit as soon as it finds a value that evenly divides n.

import math

try:
    n = int(input("Enter a positive whole number greater than 2: "))
    if n <= 2:
        print("Please enter a number greater than 2.")

    else:
        is_prime = True # We assume the number is prime until we find a divisor

        limit = int(math.sqrt(n)) # Calculate the upper limit for checking divisors

        for i in range(2, limit + 1):
            if n % i == 0:
                print(f"{n} is not prime (it is divisible by {i}).")
                is_prime = False
                break

        # If no divisor was found
        if is_prime:
            print(f"{n} is prime.")

except ValueError:
    print("Invalid input. Please enter a whole number.")

# Enter a positive whole number greater than 2: 1
# Please enter a number greater than 2.
# Enter a positive whole number greater than 2: 3
# 3 is prime.
# Enter a positive whole number greater than 2: 10
# 10 is not prime (it is divisible by 2).