# -*- coding: utf-8 -*-
"""Yin_Htwe_Ch7ProgrammingExercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWCBa36FqTs8dXNyjbfiq-i4IuAbLtic
"""

#1.A program which accepts an exam score as input and uses adecsion structure to calculate the corresponding grade

exam_score = int(input("Enter the exam score: "))

if exam_score >= 90:
    grade = "Your grade is A."

elif exam_score >= 80:
    grade = "Your grade is B."

elif exam_score >= 70:
    grade = "Your grade is C."

elif exam_score >= 60:
    grade = "Your grade is D."

else:
    grade = "Your grade is F."

print("The Answer:", grade)

# Enter the exam score: 90
# The Answer: Your grade is A.

# Enter the exam score: 89
# The Answer: Your grade is B.

# Enter the exam score: 79
# The Answer: Your grade is C.

# Enter the exam score: 69
# The Answer: Your grade is D.

# Enter the exam score: 60
# The Answer: Your grade is D.

# Enter the exam score: 59
# The Answer: Your grade is F.

#2. A program that calculates class standing from the number of credits earned.

credits = int(input("Enter the number of credits earned: "))

if credits < 7:
    class_standing = "Freshman."

elif credits < 16:
    class_standing = "Sophomore."

elif credits < 26:
    class_standing = "Junior."

else:
    class_standing = "Senior."

print("Your class standing is", class_standing)

# Enter the number of credits earned: 3
# Your class standing is Freshman.

# Enter the number of credits earned: 13
# Your class standing is Sophomore.

# Enter the number of credits earned: 40
# Your class standing is Senior.

# Enter the number of credits earned: 22
# Your class standing is Junior.

#3. A program that calculates whether a year is a leap year.

year = int(input("Enter a year: "))

if year % 400 == 0:
    print(year, "is a leap year.")

elif year % 100 == 0:
    print(year, "is not a leap year.")

elif year % 4 == 0:
    print(year, "is a leap year.")

else:
    print(year, "is not a leap year.")

# Enter a year: 2025
# 2025 is not a leap year.

# Enter a year: 1800
# 1800 is not a leap year.

# Enter a year: 1900
# 1900 is not a leap year.

# Enter a year: 1600
# 1600 is a leap year.

# Enter a year: 2000
# 2000 is a leap year.

#4 . A program that calculates a person's BMI and prints a message telling whether they are above, within, or below the healthy range.

weight = float(input("Enter your weight in pounds: "))
height = float(input("Enter your height in inches: "))

bmi = (weight * 720) / (height ** 2)

if bmi < 19:
    situation = "below healthy range"

elif 19 <= bmi <= 25:
    situation = "within healthy range"

else:
    situation = "above healthy range"

# Print results
print(f"Your BMI is {bmi:.2f}.And your health situation is {situation}.")

# Your BMI is 22.50.And your health situation is within healthy range.